# Generated by Django 3.2.12 on 2022-02-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todolist_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
